import {
  Heading,
  Box,
  Link,
  Flex,
  Spacer,
  useColorMode,
  Button,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  Stack, Alert, AlertIcon,
} from '@chakra-ui/react';
import { useRouter } from 'next/router';
import useTranslation from 'next-translate/useTranslation';
import { default as NextLink } from 'next/link';
import { MoonIcon, SunIcon, ChevronDownIcon } from '@chakra-ui/icons';
import setLanguage from 'next-translate/setLanguage';
import Footer from '@/components/Footer';
import Head from 'next/head';
// import styles from '@/styles/Home.module.css';
import { useAccount, useNetwork } from 'wagmi';
import { NavLink } from '@/components';
import { defaultChain } from '@/utils/contract';

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const { address, connector, isConnected } = useAccount();
  const { chain } = useNetwork();
  const router = useRouter();
  const { t, lang } = useTranslation('common');
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Head>
        <title>{t('nav.HEADING')}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/*<SwitchNetworkAlert />*/}
      {/*<MetaMaskLeadBanner />*/}
      <Box px={8} bg={isConnected ? '#88ff8811' : '#ff888811'} position={'static'}>
        <Flex>
          <Box p={2}>
            <Link as={NextLink} href='/' locale={router.locale}>
              <Heading size='md'>
                <pre>{t('nav.HEADING')}</pre>
              </Heading>
            </Link>
          </Box>
          <Spacer />
          <Stack alignItems={'center'} direction='row' spacing={4}>
            <NavLink href='/'>
              {t('nav.HOME')}
            </NavLink>
            <NavLink href={'/quests'}>
              {t('nav.QUESTS')}
            </NavLink>
            <NavLink href='/faucet'>
              {t('nav.FAUCET')}
            </NavLink>
          </Stack>
          <Spacer />
          <Stack alignItems={'center'} direction='row' spacing={4}>
            <Menu>
              <MenuButton
                colorScheme={
                  isConnected && chain?.id == defaultChain.id
                    ? 'green'
                    : isConnected
                      ? 'orange'
                      : 'red'
                }
                as={Button}
                rightIcon={<ChevronDownIcon />}
              >
                {isConnected ? `Connected to ${chain?.name}` : t('nav.WALLET__NOT_CONNECTED')}
                {/*{t('TOOL_LINK')}*/}
              </MenuButton>
              <MenuList>
                <MenuItem
                  onClick={(event)=>{
                    event.preventDefault();
                    router.push('/wallet')
                    event.stopPropagation();
                  }}
                >
                  <Link>{t('nav.WALLET__SETTINGS')}</Link>
                </MenuItem>
              </MenuList>
            </Menu>
            <NavLink href='/admin'>
              {t('nav.ADMIN')}
            </NavLink>
            <Button size='md' onClick={toggleColorMode} p={4}>
              {colorMode == 'dark' ? <SunIcon /> : <MoonIcon />}
            </Button>
            <Button size='md' onClick={async () => await setLanguage(lang == 'en' ? 'ja' : 'en')}>
              {lang == 'en' ? '日本' : 'En'}
            </Button>
          </Stack>
        </Flex>
      </Box>
      <Box p={5} minH={'80vh'}>
        {!isConnected && <Alert status={'error'}>
          <AlertIcon />
          {t('wallet.CONNECT_TO_CONTINUE')}
        </Alert>}
        {isConnected && chain?.id !== defaultChain.id && <Alert status={'warning'}>
          <AlertIcon />
          {t('wallet.CONNECTED_TO_DIFFERENT_CHAIN')}
        </Alert>}
        {children}
      </Box>
      <Footer />
    </>
  );
};

export default Layout;
